### PR TITLE
add carthage support

### PR DESCRIPTION
**Pull request by levanlongktmt**
Add xcsharedata folder to help Carthage can build the Mantis schema.

### CODE REVIEW

**Comment by guoyingtao** [comment]
Thanks for the PR.
I tried

**Comment by guoyingtao** [comment]
Thanks for the PR. @levanlongktmt 
I tried to build Mantis via Carthage, and this error showed up:

> *** Skipped building Mantis due to the error:
> Dependency "Mantis" has no shared framework schemes for any of the platforms: iOS
> 

I found a solution here and it worked.
https://github.com/patchthecode/JTAppleCalendar/issues/1159#issuecomment-544132022

Would you mind updating the README based on this solution. Thanks!

**Comment by levanlongktmt** [comment]
@guoyingtao by default Carthage will build the newest `release` tag. In this case it use tag `0.43` and this version doesn't support carthage so it will show error when build.
I updated the README, but you should also update it in next tag.

**Comment by guoyingtao** [comment]
@levanlongktmt I think you are right. I will update it in next tag. Thank you!

**Pull request merged**
