### PR TITLE
Add config setting to hide toolbar and make button handlers public

### PR DESCRIPTION
**Pull request by mschonvogel**
In order to be able to implement a custom toolbar, I added the config option to hide the default toolbar and made the toolbar button's handlers public.

### CODE REVIEW

**Comment by guoyingtao** [comment]
@mschonvogel  
Thanks for the PR. I think it may be not the best way to let users to create a custom toolbar by simply hiding the original one. It seems not very convenient for users also we still doing the work for the hidden toolbar.

Do you want to just change the texts/icons for the toolbar buttons? If so, maybe we can refactor CropToolbar to expose some methods to give users changes to customize those buttons.

**Comment by mschonvogel** [comment]
I want to: Use custom button classes, change the order of buttons, change the layout of the toolbar bar, etc.

I reckon it'd be quite hard to give the users this flexibility, and, in my opinion, it's not what the library should be doing. Maybe it's best to completely separate the toolbar from the library and just add it in the example app.

**Comment by guoyingtao** [comment]
@mschonvogel Thanks for the suggestion. The current toolbar provides some default implementation which is convenient for users. Like when you choose a fixed ratio, the ratio button will become blue to show it is using the fixed ratio. It changes white when you click it again.
Also, some users may just want to crop a image without working on UI part, Mantis may also be convenient for them.
I may make it more customizable in the future releases.

**Comment by mschonvogel** [comment]
I need full flexibility, just allowing customized buttons is not enough for my use case (and probably for most developers who have a designer in the team and have to implement designs accurately.

I understand that there are also a lot of users who want to just use this component without having to deal with the UI. For those users, you could offer some kind of "DefaultCropViewController" with a Toolbar that adds the "CropViewController" as a child view controller.

**Comment by guoyingtao** [comment]
@mschonvogel Good suggestion! I may add this feature in a future release.

**Comment by mschonvogel** [comment]
@guoyingtao That'd be great!

**Comment by guoyingtao** [comment]
@mschonvogel I release Mantis 1.1.0 with a CustomizedCropToolbar conform to **CropToolbarProtocol** in the example project.

**Pull request closed without merging**
