### PR TITLE
fix: fix initial view show-up issue for preset transformation

### PR DESCRIPTION
**Pull request by guoyingtao**

### CODE REVIEW

**Comment by xinatanil** [comment]
Not exactly what I meant, now it's just a black screen and then the image appears (with correct crop info).
Possibly, because all the adjustments are being applied at viewDidAppear. Any chance to move the logic to viewWillAppear?

**Comment by guoyingtao** [comment]
@xinatanil 
I updated the code. I think this time it should work.

Simulator Screen Recording - iPhone 15 Pro Max - 2023-11-01 at 21 23 45

**Comment by xinatanil** [comment]
Now it works as expected
Thanks!

**Review by xinatanil — APPROVED** [review]
Works as expected 🔥

**Pull request merged**
