### PR TITLE
Added support to make the VisualEffect changeable

### PR DESCRIPTION
**Pull request by codebeauty**
To enable Mantis to fit into different types of iOS apps the developer should be able to change also the appearance of the cropper. The visual style is currently fixed and does not fit in any type of app.

Without too much effort this small addon introduce the **CropVisualEffectType** which also can be .none to make the cropper more minimalistic in style.

**What I did:**
1. added cropVisualEffectType as new Config attribute
2. added CropVisualEffectType
3. added two examples into the Mantis example app.

👍 Keep up the good work on the ✂️cropper.

**👉 Example of CropVisualEffectType .blurDark**

Blurred Dark is the default style type.

Simulator Screen Shot - iPhone 11 Pro - 2020-09-29 at 17 33 50

**👉 Example of CropVisualEffectType .none**

Simulator Screen Shot - iPhone 11 Pro - 2020-09-29 at 17 33 43

### CODE REVIEW

**Comment by guoyingtao** [comment]
Thanks for the PR.

I tested the new effects and found
* The blurLight makes the rotation board harder to see. (as shown in the picture below)
* No blur effect does not make a big difference.

So I think it may not be a good idea to add CropVisualEffectType to Mantis for now.

image

**Comment by codebeauty** [comment]
You are right the readability on .blurLight is bad. 

For my personal use is **.none** the best solution. I added the other types to provide a more flexible solution.

What about a more simple solution by a way the developer can just turn the blur effect off. 🤗 I would provide a pull request.

**Comment by guoyingtao** [comment]
If **.none** is the best solution for you, you can just remove .blurLight effect and update the example. Maybe we can more better blur effects in the future.

**Comment by guoyingtao** [comment]
@codebeauty When using .none VisualEffect, the image shows outside of the crop area after rotating.
image

The normal one should be like this.
image

**Comment by codebeauty** [comment]
Sorry, I've overlooked that behavior. Fixed in the latest commit. 🤞

**Comment by guoyingtao** [comment]
Looks good. Thanks for the PR.

**Pull request merged**
