### PR TITLE
Allow to select free ratio

### PR DESCRIPTION
**Pull request by Karllas**
Allow to select free ratio if config.presetFixedRatioType is equal. to.canUseMultiplePresetFixedRatio(defaultRatio: 0)

### CODE REVIEW

**Comment by guoyingtao** [comment]
@Karllas 
Can you give me an example how you want to use didSelectFreeRatio?

**Comment by Karllas** [comment]
We don't use Mantis' toolbar and there was no way to programmatically set the free ratio so we came up with this solution

**Comment by Karllas** [comment]
It's a button on a custom toolbar. It can clicked by the user

**Review by guoyingtao — APPROVED** [review]
Looks good

**Pull request merged**
