### PR TITLE
Added support for Theme Color

### PR DESCRIPTION
**Pull request by ejuden**
Using Theme Colors on View and Toolbar

### CODE REVIEW

**Comment by ejuden** [comment]
Forgot to add how it's used:

`config.themeColor = UIColor(named: "ThemeColor")!`
`config.cropToolbarConfig.themeColor = UIColor(named: "ThemeColor")!`
`config.cropVisualEffectType = .custom(color: UIColor(named: "ThemeColor")!)`

**Comment by guoyingtao** [comment]
> Forgot to add how it's used:
> 
> `config.themeColor = UIColor(named: "ThemeColor")!`
> `config.cropToolbarConfig.themeColor = UIColor(named: "ThemeColor")!`
> `config.cropVisualEffectType = .custom(color: UIColor(named: "ThemeColor")!)`

@ejuden 
Looks good!
One suggestion. Can you make the theme setting a little bit simpler? For example, we only set config.themeColor, then config.cropToolbarConfig.themeColor and config.cropVisualEffectType can be set automatically.
Also, can you add a new demo for this feature to the Example project? Thanks!

**Comment by ejuden** [comment]
I will be glad to, but you think any user might want to separate the
toolbar, view and mask colors?
I have mine where I can make them different colors.

**Comment by guoyingtao** [comment]
> I will be glad to, but you think any user might want to separate the toolbar, view and mask colors? I have mine where I can make them different colors.
> […](#)

Maybe we can add a new property CropViewBackgroundColor to Mantis.Config
If any user wants to separate the toolbar, view and mask colors, then the user just need to set them separately (CropViewBackgroundColor/config.cropToolbarConfig.themeColor/config.cropVisualEffectType)

**Comment by guoyingtao** [comment]
Since this ticket hasn't been discussed for a long time, I will close it for now. You can reopen it in the future if needed.

**Pull request closed without merging**
